title: Bensuperpc's website
description: Its my new website :3
theme: just-the-docs

url: https://bensuperpc.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
