title: Bensuperpc's website
description: Its my new website :3
theme: just-the-docs
baseurl: ""
url: https://bensuperpc.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

back_to_top: true
back_to_top_text: "Back to top"

color_scheme: nil

